#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CSHowDoISamples.Resource", IsApplication=true)]

namespace CSHowDoISamples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.Compass = global::CSHowDoISamples.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default256x256 = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default512x512 = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe_Pressed = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_noImageTile = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.Compass = global::CSHowDoISamples.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default256x256 = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default512x512 = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe_Pressed = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_noImageTile = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::CSHowDoISamples.Resource.Drawable.icon_mapsuite_Plus_Pressed;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int buttonbackground = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonselectedbackground = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Circle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Clear = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Compass = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Cursor = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Draw = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Edit = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Ellipse = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Expand = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_mapsuite_default256x256 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_mapsuite_default512x512 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_mapsuite_globe = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_mapsuite_globe_Pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_mapsuite_Minus = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_mapsuite_Minus_Pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_mapsuite_noImageTile = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_mapsuite_Plus = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon_mapsuite_Plus_Pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Line = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int linearlayoutshape = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int MapSuite = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Notice = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Pin = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Point = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Polygon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Rectangle = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int save = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Square = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ThinkGeoLogo = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MainLayout = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int androidmap = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int contentLinearLayout = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int contentRelativeLayout = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int descriptionTextView = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int headerRelativeLayout = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int instructionLinearLayout = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int instructionTextView = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int localWebView = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int uploadDataTextView = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int uploadProgressBar = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int viewSource = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DisplayMapView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Instruction = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SplashLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Tree = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int WebView = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int ActionBarMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
